# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from tests.grpc_codegen import test_pb2 as test__pb2


class TestServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetUser = channel.unary_unary(
        '/test.TestService/GetUser',
        request_serializer=test__pb2.GetPayload.SerializeToString,
        response_deserializer=test__pb2.User.FromString,
        )
    self.ListUsers = channel.unary_stream(
        '/test.TestService/ListUsers',
        request_serializer=test__pb2.Empty.SerializeToString,
        response_deserializer=test__pb2.User.FromString,
        )


class TestServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListUsers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TestServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetUser,
          request_deserializer=test__pb2.GetPayload.FromString,
          response_serializer=test__pb2.User.SerializeToString,
      ),
      'ListUsers': grpc.unary_stream_rpc_method_handler(
          servicer.ListUsers,
          request_deserializer=test__pb2.Empty.FromString,
          response_serializer=test__pb2.User.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'test.TestService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
